<?php

/*
 * Editor server script for DB table ss_sections
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
Editor::inst( $db, 'ss_sections' )
	->fields(
		Field::inst( 'year' )
			->validator( 'Validate::minMaxLen_required', array('min'=>4, 'max'=>4 ) ),
		Field::inst( 'season' )
			->validator( 'Validate::required' ),
		Field::inst( 'name' )
			->validator( 'Validate::required' ),
		Field::inst( 'open' )
			->validator( 'Validate::required' )
	)
	->process( $_POST )
	->json();

