<?php

/*
 * Editor server script for DB table ss_teams
 * Automatically generated by http://editor.datatables.net/generator
 */

// DataTables PHP library
include( "lib/DataTables.php" );

// Alias Editor classes so they are easy to use
use
	DataTables\Editor,
	DataTables\Editor\Field,
	DataTables\Editor\Format,
	DataTables\Editor\Join,
	DataTables\Editor\Validate;


// Build our Editor instance and process the data coming from _POST
$editor = Editor::inst( $db, 'ss_teams' )
	->fields(
		Field::inst( 'section_id' ),
		Field::inst( 'name' ),
		Field::inst( 'notes' )
	);
// The "process" method will handle data get, create, edit and delete
// requests from the client
$out = $editor
    ->process($_POST)
    ->data();

	
//	ORDER BY year DESC, season DESC, id ASC
// When there is no 'action' parameter we are getting data, and in this
// case we want to send extra data back to the client, with the options
// for the 'Sea' select list
if ( !isset($_POST['action']) ) {
	foreach ( $out['aaData'] as $aaDataID => $team ) {
		$sectionNameQueryString = "SELECT * FROM `ss_sections` WHERE `id` = '{$team['section_id']}' ";
		$sectionName = $db->sql($sectionNameQueryString)->fetch();
		$out['aaData'][$aaDataID]['section_name'] = $sectionName['season'].' '.$sectionName['year'].' - '.$sectionName['name'];;
	}
	
	$sectionDataQueryString = "SELECT `id` AS value, CONCAT(`year`, ' ', `season`, ' - ', `name`) AS label FROM `ss_sections` ORDER BY year DESC, season DESC, id ASC";
	$sectionData = $db->sql($sectionDataQueryString)->fetchAll();
	$out['sectionData'] = $sectionData;
} elseif($_POST['action']=='create') {
	$sectionNameQueryString = "SELECT * FROM `ss_sections` WHERE `id` = '{$_POST['data']['section_id']}'";
	$sectionName = $db->sql($sectionNameQueryString)->fetch();
	$out['row']['section_name'] = $sectionName['season'].' '.$sectionName['year'].' - '.$sectionName['name'];
} elseif($_POST['action']=='edit') {
	$sectionNameQueryString = "SELECT * FROM `ss_sections` WHERE `id` = '{$_POST['data']['section_id']}'";
	$sectionName = $db->sql($sectionNameQueryString)->fetch();
	$out['row']['section_name'] = $sectionName['season'].' '.$sectionName['year'].' - '.$sectionName['name'];
}
 
// Send it back to the client
echo safe_json_encode( $out );
?>