<?php

/*
 * DB connection script for Editor
 * Automatically generated by http://editor.datatables.net/generator
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

/*
 * Edit the following with your database connection options
 */
$sql_details = array(
	"type" => "Mysql",
	"user" => "abingdon_wp",
	"pass" => "KtJLftH]Z8[TZT]bl#",
	"host" => "localhost",
	"port" => "3306",
	"db"   => "abingdon_wp"
);

